#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
$DIR/GithubAnalysis/shell/gitStatsAll.sh $DIR/GithubAnalysis/resources/valid/stats.txt
CWD=$(pwd)
cd $DIR/GithubAnalysis/src
./main.js "$@"
FILE=../resources/output/javaOut.json
if [ -f $FILE ]; then
   mv $FILE ../../viz_metro/input.json
   cd $DIR/viz_metro
   npm start
fi
